### ISSUE TITLE
Invoking sendMessage('key') without passing undefined

### ISSUE THREAD

**Issue by NoamLoewenstern** [aklinker1/webext-core#23]
[In the docs](https://github.com/aklinker1/webext-core/blob/72b58ad2146c9e708c16393418953288b5c5d006/docs/messaging/protocol-maps.md?plain=1#L31) there's an example of invoking sendMessage with a key which doesn't need to pass data, therefore needs to pass 'undefined'.
Is there a way in TS to auto-recognize that there's no need to pass data and there won't demand passing 'undefined'? 
I've searched the internet, and seems there's a difference between making an argument optional and explicitly allowing an undefined type.
For example:
If the ProtocolMap is:
```Typescript
export interface ProtocolMap {
  foo: { id: number; name: string };
  bar: ProtocolWithReturn<string, number>;
  noDataKey: ProtocolWithReturn<undefined, number>;
}
```
Even if I want to call 'noDataKey' like this:
```typescript
sendMessage('noDataKey')
```
I can't, TS error says: `expected 2-3 arguments, but got 1. An argument for 'data' was not provided`
And so I have to pass `undefined`: 
```typescript
sendMessage('noDataKey', undefined)
```

I've realized that this issue of `assuming undefined type as optional` has been a widespread issue, but haven't managed to find out if there's a way around it, or if there's another way to address this issue.
The links I found regarding this issue:
[Here](https://github.com/microsoft/TypeScript/issues/12400)
[Here](https://github.com/microsoft/TypeScript/issues/17644)
[Here](https://github.com/microsoft/TypeScript/issues/19259)
And even in the [Design Meeting Notes](https://github.com/microsoft/TypeScript/issues/19393), adding a screenshot of the exact address of this issue:
![image](https://user-images.githubusercontent.com/6962980/226214763-8bfdd74b-2954-419b-aff0-5313a542ca48.png)

---
I found that explicitly declaring an argument as `void` will allow this!
Like so:
```typescript
function func1(name: string, age: number | undefined) {}
func1('a') // will show error "Expected 2 arguments, but got 1"

function func2(name: string, age: number | void) {}
func2('a') // will not show any error!
```
But trying to apply this to the `GetDataType` did not allow, even if TS knows it's a `void`. 
```typescript
interface ProtocolMap {
  noDataKey: ProtocolWithReturn<void, number>;
}
// ...
sendMessage('noDataKey') // Still error "Expected 2-3 arguments", even though ts recognizes it as void, as the following image shows:
```
![image](https://user-images.githubusercontent.com/6962980/226215085-e5cd141a-e678-414d-8774-25cfdc2b345b.png)

Maybe worth looking into it?

**Comment by aklinker1** [comment]
I could easily add an override that would allow only 1 argument to be passed:

```ts
function sendMessage<T extends KeyOfWithNoData<ProtocolMap>>(
  type: T,
  tabId?: number,
): Promise<GetReturnType<ProtocolMap, T>>;

function sendMessage<T extends keyof ProtocolMap>(
  type: T,
  data: GetDataType<ProtocolMap, T>,
  tabId?: number,
): Promise<GetReturnType<ProtocolMap, T>>;
```

> The `KeyOfWithNoData` type is complex, I've hidden the implementation in this example. Just know compared to `keyof`, it would only return keys who's data is specified as `undefined`.

In fact, I did this for some projects at work when I wrote a messaging wrapper for them before I wrote this library.

So the problem isn't making the function accept a single parameter. Rather, the reason I didn't add this is because the final parameter, `tabId`, is ambiguous.

It's impossible to determine what the intent is for a call like this:

```ts
sendMessage("someMessage", 123);
```

Am I sending a message that doesn't have any payload to tab `id=123` or am I sending a message with `data=123`? Internally, the code has no way of knowing since it can't inspect types at runtime.

So I've decided to require a data parameter, even if it's `undefined`, to be explicit.
