### ISSUE TITLE
Messaging: Serialize and return the entire error to the sender

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/webext-core#36]
Currently, when an error is thrown by a `onMessage` handler, only the error message is returned to the sender. We can use [`serialize-error`](https://www.npmjs.com/package/serialize-error) to serialize and de-serialize the error so we send the full error (including the stacktrace) back to the sender.

**Comment by aklinker1** [comment]
Released in [`v1.4.0`](https://github.com/aklinker1/webext-core/releases/tag/messaging-v1.4.0)

**Comment by rxliuli** [comment]
I was wondering if there are plans to support custom serialization tools, which are necessary for handling more complex data structures like `Request/Response`.
