### ISSUE TITLE
Can't install any package.

### ISSUE THREAD

**Issue by DeKleineKobini** [aklinker1/webext-core#41]
Executing `npm i @webext-core/proxy-service` results in an error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@webext-core%2fproxy-service - Not found
npm ERR! 404
npm ERR! 404  '@webext-core/proxy-service@^1.2.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I've also tried @webext-core/match-patterns, which has the same problem. Non-related packages install just fine so that's not the issue either.

**Comment by aklinker1** [comment]
Huh, interesting. I just ran the command and it's working just fine. It's hosted on NPM, so this seems like a local networking problem or an intermittent error on NPM's side.

```sh
$ npm i @webext-core/proxy-service

added 7 packages, and audited 8 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by aklinker1** [comment]
Here's the response for that 404 URL, it's not a 404 for me. Maybe try a different network or device?

![Screen Shot 2023-07-14 at 5 13 40 PM](https://github.com/aklinker1/webext-core/assets/10101283/110dfffe-f103-4d48-bf1a-b98d1ba3128b)

**Comment by DeKleineKobini** [comment]
I don't believe it was on my side, as I noticed it due to my Github Action failing to install it as well, but it seems like it was only temporary as when I tried it again just now it did work just fine.
