### ISSUE TITLE
@webext-core/fake-browser don't mock the webextension-polyfill with vitest

### ISSUE THREAD

**Issue by kayac-chang** [aklinker1/webext-core#43]
## Description

The mocking functionality no longer works.
The following is the error we encountered in the vitest.

```
Error: This script should only be loaded in a browser extension.
 ❯ node_modules/webextension-polyfill/dist/browser-polyfill.js:10:9
 ❯ node_modules/webextension-polyfill/dist/browser-polyfill.js:5:5
 ❯ Object.<anonymous> node_modules/webextension-polyfill/dist/browser-polyfill.js:13:3
```
## Dependencies

- "@types/webextension-polyfill": "^0.10.5"
- "@webext-core/fake-browser": "^1.2.2"
- "typescript": "^5.2.2"
- "vite": "^4.4.9"
- "vitest": "^0.34.5"
- "@webext-core/storage": "^1.1.3",
- "webextension-polyfill": "^0.10.0"

## Steps To Reproduce

I follow the [documentation](https://webext-core.aklinker1.io/guide/fake-browser/testing-frameworks.html#vitest) with a minimal setup.

Also, provide the repository 
https://github.com/kayac-chang/webext-core-fake-browser-test

**Comment by aklinker1** [comment]
> - "@types/webextension-polyfill": "^0.10.5"
> - "@webext-core/fake-browser": "^1.2.2"
> - "typescript": "^5.2.2"
> - "vite": "^4.4.9"
> - "vitest": "^0.34.5"
> - "@webext-core/storage": "^1.1.3",
> - "webextension-polyfill": "^0.10.0"

Can you add your lockfile to the reproduction? Otherwise I might be using different versions of these dependencies.

I haven't updated the fake-browser package for a while, so it's likely something Vitest broke, but let me check it out.

**Comment by aklinker1** [comment]
Related to https://github.com/vitest-dev/vitest/issues/3936#issuecomment-1739836844.

```patch
diff --git a/vitest.config.ts b/vitest.config.ts
index 7f3ee78..6c7b4f1 100644
--- a/vitest.config.ts
+++ b/vitest.config.ts
@@ -7,5 +7,10 @@ export default defineConfig({
   test: {
     globals: true,
     setupFiles: ["vitest.setup.ts"],
+    server: {
+      deps: {
+        inline: ["@webext-core/storage"],
+      },
+    },
   },
 });
```

**Comment by aklinker1** [comment]
I've updated the docs. Read them here: https://webext-core.aklinker1.io/guide/fake-browser/testing-frameworks.html#vitest

https://github.com/aklinker1/webext-core/commit/3f7187d75ad0cbf557b6d5484e367dac83670854

**Comment by kayac-chang** [comment]
It works now! Thank you @aklinker1.
