### ISSUE TITLE
`@webext-core/messaging` errors with `No response` when return value contains function

### ISSUE THREAD

**Issue by lionelhorn** [aklinker1/webext-core#55]
First, many thanks to the contributors ! Nice project and utils 👍 

I'm using a content script in main world context to dynamically extract "react props" from the whole dom tree for use in another content script not running in main world context.

In console logs the following abreviation stands for
MW: Main World
CS: Content Script

Messenger caller is in a CS without MW context

###  Failing: with error thrown but error message doesn't explain why `No response`

Error message just says
```shell
chunk-ALTBYIMW.js:80 Uncaught (in promise) Error: No response
    at Object.<anonymous> (chunk-ALTBYIMW.js:80:92)
    at Generator.next (<anonymous>)
    at fulfilled (chunk-ALTBYIMW.js:37:19)
```

The issue is that the return value object contains a function.

Example simplified code :

```ts
mainWorldMessenger.onMessage("test", (data) => {
  const props = [
    {
      "className": "ml-md",
      onClick: () => {
      }
    }
  ]

  const ret = {reactProps: props};
  log("return value will be", ret)

  return ret
});
```
<img width="425" alt="image" src="https://github.com/aklinker1/webext-core/assets/50528276/706d6e4a-5b33-4291-95b9-586672414f11">

### Working: messenger func returns with value
```ts
mainWorldMessenger.onMessage("test", (data) => {
  const props = [
    {
      "className": "ml-md",
    }
  ]

  const ret = {reactProps: props};
  log("return value will be", ret)

  return ret
});
```

<img width="411" alt="image" src="https://github.com/aklinker1/webext-core/assets/50528276/37e278ba-d464-4a1c-a792-202126b0764f">

### Solution
Return value can be sanitized.
**An error message from `@webext-core/messaging` explaining why it doesn't return would be nice**

**Comment by aklinker1** [comment]
Interesting, I would have expected it to not error out when passing a function, but for the function to silently be removed from the response.

I'll see if I can figure out why a response isn't returned in this case and improve the error message.

**Comment by 1natsu172** [comment]
One issue with window messaging should be clean. I'll take a look at this issue when I have some free time.

**Comment by 1natsu172** [comment]
Alright, `postmessage` and `dispatchEvent` execute structured clone, so we need to check before sending. https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

I'll create a PR.

**Comment by aklinker1** [comment]
Released in https://github.com/aklinker1/webext-core/releases/tag/messaging-v2.1.0
