### ISSUE TITLE
@webext-core/messaging errors with No response when sending data back from an injected script

### ISSUE THREAD

**Issue by rcoopr** [aklinker1/webext-core#57]
Using only example code from the [webext-core site](https://webext-core.aklinker1.io/guide/messaging/), injected script messaging causes an error (No error when sending messages *to* the injected script)
Potentially related to #55 ?

Error: 
```
Uncaught (in promise) Error: No response
    at Object.<anonymous> (chunk-ALTBYIMW.js:80:67)
    at Generator.next (<anonymous>)
    at fulfilled (chunk-ALTBYIMW.js:36:24)
```

Minimal repro: https://github.com/rcoopr/wxtcore-messaging-repro
  - clone
  - `pnpm i`
  - `pnpm dev`
  - check console

What steps did I do to create example:
  - init WXT using `pnpm dlx wxt@latest init <project-name>`
  - `pnpm i @webext-core/messaging`
  - Add permissions for injected script to wxt config
  - Copy code from https://webext-core.aklinker1.io/guide/messaging/#window-messaging (Also, there is a typo, `browser.runtime.getUrl` is actually `getURL`)
  - run `pnpm dev` and check console

The messages are recieved, yet there is an error anyway. The issue is also present in the built output. Only tested on Chrome 122

**Comment by rcoopr** [comment]
More vague details: I have also tried switching to window messaging, but had issues in the *other* direction - sending messages to the injected script. However, I have not made a minimal repro and don't remember the specifics - it may have been user error

**Comment by maaasyn** [comment]
I can confirm, same issue on my side. I try to communicate from pop up to injected script and vice versa.

**Comment by drbolsen** [comment]
The same issue here with WindowMessaging, below is a detailed report 

### Describe the bug

I got a weird error with WindowMessaging

```Javascript
Error: No response at Object.<anonymous> (chrome-extension://hfpnfjaneoimodeagddennghcdfanldp/c…}
content.js:1 Uncaught (in promise) Error: No response
    at Object.<anonymous> (content.js:1:3870)
    at Generator.next (<anonymous>)
    at p (content.js:1:3308)
(anonymous) @ content.js:1
p @ content.js:1
await in p (async)
(anonymous) @ VM336:1
Promise.then (async)
(anonymous) @ VM336:1
```

A very simple setup - an injected script and a content script, each side has an instance of messenger, a listener and a function that sends a message to other side.  When a message is sent from the injected script to the content script everything is fine, however every time when a message is sent from the content script to the injected script I get  the error.

The actual code is below

_messaging.ts_
```Typescript
export interface TestProtocol {
    sendHello(msg: string): void
    sendGoodbye(msg: string): void
}
```
_injected.ts_
```Typescript
import { defineWindowMessaging } from "@webext-core/messaging/page"
import { TestProtocol } from "@/messaging"
export default defineUnlistedScript(() => { 
    const messenger = defineWindowMessaging<TestProtocol>({ namespace: 'my_test_namespace', logger: console})
    messenger.onMessage('sendGoodbye', (data): void => {
        console.log('Received : ', data)
    })
    return {
        sendHello: (): void => { 
            messenger.sendMessage('sendHello', 'hello!').then(() => {
                console.log('Sent hello!')
            })
        }
    }
})
```

_content.ts_
```Typescript
import { defineWindowMessaging } from "@webext-core/messaging/page";
import { TestProtocol } from "@/messaging";

export default defineContentScript({
  main() {
    const messenger = defineWindowMessaging<TestProtocol>({ namespace: 'my_test_namespace', logger: console })
    // Inject our dom script for communications.
    const injectScript = (url: string): void => {
      <... skipped...> 
    }
    if (document instanceof Document) {
      injectScript(chrome.runtime.getURL('injected.js'))
    }

    messenger.onMessage('sendHello', (data):void => {
      console.log('Recieved :', data)
    })

    return {
      sendGoodbye: (): void => {
        messenger.sendMessage('sendGoodbye', 'bye').then(() => {
          console.log('Message sent')
        })
      }
    }
  }
});
```
Note, that I exposed sendGoodbye and sendHello so I can easy test it in Chrome's console. 

Now, when I call sendHello from the injected script context, it works as it should
```
_injected.then((i) => { i.sendHello() })

injected.js:1 [messaging] sendMessage {id=8607} ─ᐅ {id: 8607, type: 'sendHello', data: 'hello!', timestamp: 1717072633884}
Promise {<fulfilled>: undefined}
<---note order --->
content.js:1 [messaging] Received message {id: 8607, type: 'sendHello', data: 'hello!', timestamp: 1717072633884} 
content.js:1 Recieved : {id: 8607, type: 'sendHello', data: 'hello!', timestamp: 1717072633884}  
content.js:1 [messaging] onMessage {id=8607} ─ᐅ {res: undefined}
<--- response part --->
injected.js:1 [messaging] Received message {id: 8607, type: 'sendHello', data: 'hello!', timestamp: 1717072633884} 
injected.js:1 [messaging] sendMessage {id=8607} ᐊ─ {res: undefined, err: undefined}
injected.js:1 Sent hello!
```
However when I call sendGoodbye from the content script context, it fails. Note that the message goes through and received, but it appears that response back order is messed up somehow
 
```
_content.then((i) => { i.sendGoodbye() })

content.js:1 [messaging] sendMessage {id=3206} ─ᐅ {id: 3206, type: 'sendGoodbye', data: 'bye', timestamp: 1717072652064}
Promise {<fulfilled>: undefined}
<-- out of order step -->
content.js:1 [messaging] Received message {id: 3206, type: 'sendGoodbye', data: 'bye', timestamp: 1717072652064} 
injected.js:1 [messaging] Received message {id: 3206, type: 'sendGoodbye', data: 'by', timestamp: 1717072652064}
injected.js:1 Received :  {id: 3206, type: 'sendGoodbye', data: 'bye', timestamp: 1717072652064}
injected.js:1 [messaging] onMessage {id=3206} ─ᐅ {res: undefined}  
<--- i guess it should appear here --->
content.js:1 [messaging] sendMessage {id=3206} ᐊ─ {res: undefined, err: Error: No response
    at Object.<anonymous> (chrome-extension://hfpnfjaneoimodeagddennghcdfanldp/c…}

content.js:1 Uncaught (in promise) Error: No response
    at Object.<anonymous> (content.js:1:3870)
    at Generator.next (<anonymous>)
    at h (content.js:1:3308)
(anonymous) @ content.js:1
h @ content.js:1
Promise.then (async)
sendGoodbye @ content.js:1
(anonymous) @ VM277:1
Promise.then (async)
(anonymous) @ VM277:1
```

### Expected behavior

No error thrown 

### Environment

```
Chrome: 125.0.6422.113
 wxt: ^0.18.0 => 0.18.3
@webext-core/messaging: "^1.4.0",
```

**Comment by aklinker1** [comment]
Thanks for the additional info everyone! Looked into this today, and it appears the messenger instance that sends the message is responding to the message with `undefined`, instead of the second instance in a different context, causing the error.

So for the window messenger, each instance just needs to ignore messages sent by itself.

**Comment by rcoopr** [comment]
> So in addition to a namespace, each messenger also needs an ID to check where the message came from, and if the sender ID is the same as the instance ID, the message should be ignored.

Is that to be implemented in userland or can it be implemented internally?

**Comment by 1natsu172** [comment]
I encountered this problem too. Seems to be with message transactions and bi-directional messaging. I'll look at the code in a bit.… 👀

**Comment by aklinker1** [comment]
> I encountered this problem too. Seems to be with message transactions and bi-directional messaging. I'll look at the code in a bit.… 👀 

Good luck lol. This is the code I'm least proud of 🫡

**Comment by 1natsu172** [comment]
Haha, codes was complicated than I thought lol. But there are so many pitfalls in messaging that rewrites don't seem to be easy.

**Comment by aklinker1** [comment]
Yeah, I did a bad job extracting the transport layer and reusing the messaging logic between the different ways of sending messages :/

**Comment by 1natsu172** [comment]
Alright, I found one more problem that lazy `onMessage`. 

If do awaited `sendMessage` on the CS side and then do `onMessage`, the message not be received. The current implementation doesn't have handshake and polling, so all onMessage must be done first on both sides. Otherwise, the message will be unreachable.

#### injected script

```typescript
export default defineUnlistedScript(async () => {
  console.log('[google-injected.ts] Injected script loaded');

  googleMessaging.onMessage('ping', event => {
    console.log('[google-injected.ts] Received', event);
    return 'pong';
  });

  googleMessaging.onMessage('ping2', event => {
    console.log('[google-injected.ts] Received2', event);
    return 'pong2';
  });

  // The receiver is not there yet.
  googleMessaging.sendMessage('fromInjected', undefined).then(res => {
    console.log('[google-injected.ts] Response:', res);
  });

  // The receiver is not there yet.
  const res2 = await googleMessaging.sendMessage('fromInjected2', undefined);
  console.log('[google-injected.ts] Response2:', res2);
});
```

#### content-scirpt

```ts
export default defineContentScript({
  matches: ['*://*.google.com/*'],

  main(ctx) {
    console.log('[google.content.ts] Content script loaded');

    const script = document.createElement('script');
    script.src = browser.runtime.getURL('/google-injected.js');
    script.onload = async () => {
      const res = await googleMessaging.sendMessage('ping', undefined);
      console.log('[google.content.ts] Response:', res);

      const res2 = await googleMessaging.sendMessage('ping2', undefined);
      console.log('[google.content.ts] Response2:', res2);

      // ! Message has already been sent.
      googleMessaging.onMessage('fromInjected', event => {
        console.log('[google.content.ts] Received:', event);
        return 'hello injected';
      });

      // ! Message has already been sent.
      googleMessaging.onMessage('fromInjected2', event => {
        console.log('[google.content.ts] Received:', event);
        return 'hello injected2';
      });
    };
    document.head.appendChild(script);
  },
});
```

![image](https://github.com/user-attachments/assets/bc08f24a-099a-4907-b882-6dc45b5a9302)

**Comment by 1natsu172** [comment]
Oops, on second thought, this was a different Issue from this Issue.

**Comment by 1natsu172** [comment]
I'm working on PR for this mix up issue. Not sure if it will work yet 💦

**Comment by 1natsu172** [comment]
I feel I could fix it, so I will submit a PR.
