### ISSUE TITLE
missing dependency "serialize-error" for @webext-core/messaging

### ISSUE THREAD

**Issue by windmillcode0** [aklinker1/webext-core#73]
"serialize-error": "^11.0.3", adding to dependencies in package.json for the @webext-core/messaging package solves the issue

**Comment by 1natsu172** [comment]
@windmillcode0 I've seen this problem too and have now created an issue in upstream for a possible bug in pnpm. https://github.com/pnpm/pnpm/issues/8678

The workaround fix is to use `pnpm i --fix-lockfile`.

**Comment by 1natsu172** [comment]
Are you using the pnpm?

**Comment by windmillcode0** [comment]
Yes I am

**Comment by aklinker1** [comment]
@windmillcode0 Try v2.0.2, just released it.

**Comment by aklinker1** [comment]
This seems to be an issue with releasing packages with `bun publish` instead of using `npm publish`. Reverted to using NPM
