### ISSUE TITLE
some trouble

### ISSUE THREAD

**Issue by Xdy1579883916** [aklinker1/webext-core#77]
https://github.com/aklinker1/webext-core/blob/27203014ce91e49184ca89a43eb0adaa910448e0/packages/messaging/src/generic.ts#L137

您好，我在使用消息通讯包的时候，遇到了点麻烦。
﻿
简而言之，公司的旧版本插件我在改造的过程中，一部分使用原有的 消息通讯方案，一部分使用了 `@webext-core/proxy-service`, 显然他们的协议会有区别
﻿
我探索了源码，发现其实这里已经可以知道消息是否来自 `@webext-core/proxy-service`，或许我们可以不抛出异常，直接 `return` 或者可选地抛出异常？ 目前我打了个补丁，但是我希望这个提议可以被采纳，谢谢。

![image](https://github.com/user-attachments/assets/9a3b2109-55bd-4c1b-93b5-a21284f54a73)

Hello, I'm having some trouble using the messaging package.
﻿
In short, during the process of modifying the old version plugins of the company, some of them used the original message communication scheme, while others used '@ webext core/proxy service'. Obviously, their protocols will be different
﻿
I have explored the source code and found that it is already possible to determine whether the message is from '@ webext core/proxy service'. Perhaps we can simply 'return' without throwing an exception, or alternatively throw an exception? I have currently applied a patch, but I hope this proposal can be accepted. Thank you.

**Comment by aklinker1** [comment]
Sure, open a PR!

**Comment by aklinker1** [comment]
Released in https://github.com/aklinker1/webext-core/releases/tag/messaging-v2.1.0
