### ISSUE TITLE
Using Proxy Service in Safari throws an error if called from an Injected script

### ISSUE THREAD

**Issue by thianphat** [aklinker1/webext-core#86]
First off, thank you so much for this amazing package. I've refactored my codebase to be much more manageable and straightforward.

However, I did notice this one issue where you call a registered Proxy Service from an Injected script's UI (using React, not sure if that matters) and it throws this error. Any idea on what might be causing it? The error does not appear in Safari's console.

This works flawlessly on Chrome.

Thanks!

<img width="859" alt="Screenshot 2024-12-26 at 9 23 52 AM" src="https://github.com/user-attachments/assets/1db77743-61c6-4dac-a8c2-eebeaa74653a" />

**Comment by aklinker1** [comment]
This package uses the `webextension-polyfill`, which has some known issues with Safari and messaging. Add this code at the beginning of your background script: https://github.com/mozilla/webextension-polyfill/issues/234#issuecomment-702403327

**Comment by thianphat** [comment]
> [mozilla/webextension-polyfill#234 (comment)](https://github.com/mozilla/webextension-polyfill/issues/234#issuecomment-702403327)

added this, but it's still encountering the same error

<img width="674" alt="Screenshot 2024-12-26 at 10 00 28 AM" src="https://github.com/user-attachments/assets/83652f3a-0aa0-4ed1-a6c7-600f28189afb" />

**Comment by aklinker1** [comment]
Hmm, then I'm not sure. The error message isn't providing any useful information, so I don't even know where the problem might be

**Comment by thianphat** [comment]
I think it has to do with Safari service workers being non-responsive: https://developer.apple.com/forums/thread/764594 and not with your package itself.

**Comment by aklinker1** [comment]
OK, then I'm gonna close this issue. If you find out more and it is related to this package, feel free to reopen.
